version: '3.7'

services:
  looper:
    build: ./serviceB
    restart: always
    depends_on:
      - web
      - db
    environment:
      - SERVICE_A_URL=http://web:8080/revenue
  web:
    build: ./serviceA
    command: >
      sh -c "/app migrate &&
             /app server"
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
    environment:
      - DB_HOST=db
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=application
      - MYSQL_ROOT_PASSWORD=my-secret-pw
