apiVersion: batch/v1
kind: Job
metadata:
  name: web-migrate
spec:
  template:
    spec:
      containers:
      - name: web
        image: gcr.io/<project id>/web:v1
        command: ["/app",  "migrate"]
        env:
        - name: DB_HOST
          value: db.default.svc
      restartPolicy: OnFailure
  backoffLimit: 10
