apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: gcr.io/<project id>/web:v1
        command: ["/app", "server"]
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: db.default.svc
